### ISSUE TITLE
Spark application errors with MapR-FS client

### ISSUE THREAD

**Issue by vin4v** [HPEEzmeral/spark-on-k8s#141]
Spark-pi example errors with " java.io.IOException: Could not create FileClient err: 104"

Here is the app yaml:
=============
apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
 name: spark-pi-new
 namespace: compute
spec:
 type: Scala
 mode: cluster
 image: gcr.io/mapr-252711/spark-2.4.7:202202161825P150
 imagePullPolicy: Always
 imagePullSecrets:
  -imagepull
 mainClass: org.apache.spark.examples.SparkPi
 mainApplicationFile: "local:///opt/mapr/spark/spark-2.4.7/examples/jars/spark-examples_2.12-2.4.7.101-mapr-710.jar"
 sparkVersion: "2.4.7"
 restartPolicy:
   type: Never
 driver:
  cores: 1
  coreLimit: "1200m"
  memory: "512m"
  labels:
    version: 2.4.7
 executor:
  cores: 1
  instances: 2
  memory: "512m"
  labels:
   version: 2.4.7

Spark Operator:
==========
    Image:      gcr.io/mapr-252711/spark-operator-2.4.7:202110041001

ERROR:
=====
22/02/28 20:55:43 INFO spark.SparkContext: Added JAR file:///opt/mapr/spark/spark-2.4.7/examples/jars/spark-examples_2.12-2.4.7.101-mapr-710.jar at spark://spark-pi-new4-1646081727574-driver-svc.compute.svc:7078/jars/spark-examples_2.12-2.4.7.101-mapr-710.jar with timestamp 1646081743570
22/02/28 20:55:45 INFO k8s.ExecutorPodsAllocator: Going to request 2 executors from Kubernetes.
22/02/28 20:55:45 INFO util.Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 7079.
22/02/28 20:55:45 INFO netty.NettyBlockTransferService: Server created on spark-pi-new4-1646081727574-driver-svc.compute.svc:7079
22/02/28 20:55:45 INFO storage.BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
22/02/28 20:55:45 INFO storage.BlockManagerMaster: Registering BlockManager BlockManagerId(driver, spark-pi-new4-1646081727574-driver-svc.compute.svc, 7079, None)
22/02/28 20:55:45 INFO storage.BlockManagerMasterEndpoint: Registering block manager spark-pi-new4-1646081727574-driver-svc.compute.svc:7079 with 117.0 MB RAM, BlockManagerId(driver, spark-pi-new4-1646081727574-driver-svc.compute.svc, 7079, None)
22/02/28 20:55:45 INFO storage.BlockManagerMaster: Registered BlockManager BlockManagerId(driver, spark-pi-new4-1646081727574-driver-svc.compute.svc, 7079, None)
22/02/28 20:55:45 INFO storage.BlockManager: Initialized BlockManager: BlockManagerId(driver, spark-pi-new4-1646081727574-driver-svc.compute.svc, 7079, None)
22/02/28 20:55:45 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@3dc39459{/metrics/json,null,AVAILABLE,@Spark}
22/02/28 20:55:45 WARN fs.MapRFileSystem: Could not find any cluster, defaulting to localhost
22/02/28 20:55:54 INFO k8s.KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) ( x.x.x.x:60288) with ID 1
22/02/28 20:55:54 INFO storage.BlockManagerMasterEndpoint: Registering block manager x.x.x.x:40583 with 117.0 MB RAM, BlockManagerId(1,  x.x.x.x, 40583, None)
22/02/28 20:55:55 INFO k8s.KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) ( x.x.x.x:39872) with ID 2
22/02/28 20:55:55 INFO storage.BlockManagerMasterEndpoint: Registering block manager  x.x.x.x:43884 with 117.0 MB RAM, BlockManagerId(2,  x.x.x.x, 43884, None)
22/02/28 20:55:56 ERROR spark.SparkContext: Error initializing SparkContext.
java.io.IOException: Could not create FileClient err: 104
        at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:732)
        at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:785)
        at com.mapr.fs.MapRFileSystem.getMapRFileStatus(MapRFileSystem.java:1565)
        at com.mapr.fs.MapRFileSystem.getFileStatus(MapRFileSystem.java:1215)
        at org.apache.spark.scheduler.EventLoggingListener.start(EventLoggingListener.scala:97)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:524)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2538)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$1(SparkSession.scala:930)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
        at org.apache.spark.examples.SparkPi$.main(SparkPi.scala:30)
        at org.apache.spark.examples.SparkPi.main(SparkPi.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:855)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:943)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:952)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: Could not create FileClient err: 104
        at com.mapr.fs.MapRClientImpl.<init>(MapRClientImpl.java:148)
        at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:726)
        ... 23 more

**Comment by AlexNavara** [comment]
Hello @vin4v !
This error means that spark app could not connect to maprfs to write event logs. Make sure that the tenant exists and is configured properly, e.g., by accessing maprfs from tenantcli-0 pod:
```
kubectl exec -it tenantcli-0 -n [tenant-name] -- bash
maprlogin password
hadoop fs -ls /
```
If you don't have tenantcli-0 pod in tenant namespace - it means that your tenant is not configured with any mapr cluster, and you will not be able to write event log to maprfs. Instead, you might try to disable event logging like this:
```
spec:
  sparkConf:
    spark.eventLog.enabled: "false"
```

**Comment by vin4v** [comment]
@AlexNavara  It works fine after setting spark.eventLog.enabled: "false".
